/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.UPAO.proyecto.app;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import edu.UPAO.proyecto.ProductoController;
import edu.UPAO.proyecto.PromocionController;
import edu.UPAO.proyecto.Modelo.Producto;

/**
 *
 * @author ALBERTH
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {

        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        cargarProductosEnTabla();
        txtObservaciones.setEnabled(false);
        txtCupon.setEnabled(false);

        tablaProductos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                spCantidad.setValue(1); // 👈 Reinicia cantidad
            }
        });

    }

    public void cargarProductosEnTabla() {
        ProductoController pc = new ProductoController();
        java.util.List<edu.UPAO.proyecto.Modelo.Producto> productos = pc.cargarProductos();

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);

        for (edu.UPAO.proyecto.Modelo.Producto p : productos) {
            modelo.addRow(new Object[]{p.getNombre(), p.getPrecioVenta(), p.getStock(), p.getCodigo(), p.getVendidos()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tb_reportes = new javax.swing.JToggleButton();
        tb_entrada = new javax.swing.JToggleButton();
        tb_ventas = new javax.swing.JToggleButton();
        tb_cuenta = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        panelFormulario = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        spCantidad = new javax.swing.JSpinner();
        jButton11 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtCupon = new javax.swing.JTextField();
        rb_observacion = new javax.swing.JRadioButton();
        rb_cupon = new javax.swing.JRadioButton();
        lblTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sp_item = new javax.swing.JSpinner();
        btn_actualizarItem = new javax.swing.JButton();
        btn_eliminarItem = new javax.swing.JButton();
        btn_validar = new javax.swing.JButton();
        lbl_descuento = new javax.swing.JLabel();
        lbl_subtotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarCodigo = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosistemasempresariales/iconos/INICIO DE SESION-1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        tb_reportes.setBackground(new java.awt.Color(118, 158, 139));
        tb_reportes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tb_reportes.setText("REPORTES");
        tb_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_reportesActionPerformed(evt);
            }
        });

        tb_entrada.setBackground(new java.awt.Color(118, 158, 139));
        tb_entrada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tb_entrada.setText("R. ENT / SAL");
        tb_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_entradaActionPerformed(evt);
            }
        });

        tb_ventas.setBackground(new java.awt.Color(118, 158, 139));
        tb_ventas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tb_ventas.setText("VENTAS");
        tb_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_ventasActionPerformed(evt);
            }
        });

        tb_cuenta.setBackground(new java.awt.Color(118, 158, 139));
        tb_cuenta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tb_cuenta.setText("CUENTA");
        tb_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cuentaActionPerformed(evt);
            }
        });

        jButton1.setText("R- PRODUCTOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(tb_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(tb_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(tb_cuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregar.setBackground(new java.awt.Color(51, 204, 0));
        btn_agregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agreagar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel8.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 710, 132, 48));
        jPanel8.add(spCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 72, 48));

        jButton11.setBackground(new java.awt.Color(110, 149, 106));
        jButton11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("REPORTAR PRODUCTO");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 710, 200, 50));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jButton6.setBackground(new java.awt.Color(110, 149, 106));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("ESCANEAR SKU");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("CANCELAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButtonSiguiente.setBackground(new java.awt.Color(51, 204, 0));
        jButtonSiguiente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSiguiente.setText("SIGUIENTE");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        rb_observacion.setText("Observación");
        rb_observacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_observacionActionPerformed(evt);
            }
        });

        rb_cupon.setText("Cupón:");
        rb_cupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cuponActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotal.setText("TOTAL:");

        btn_actualizarItem.setText("Actualizar");
        btn_actualizarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarItemActionPerformed(evt);
            }
        });

        btn_eliminarItem.setText("Eliminar");
        btn_eliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(sp_item, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_actualizarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarItem)
                    .addComponent(btn_eliminarItem))
                .addContainerGap())
        );

        btn_validar.setText("VALIDAR CUP");
        btn_validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validarActionPerformed(evt);
            }
        });

        lbl_descuento.setText("Descuento");

        lbl_subtotal.setText("Subtotal:");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(rb_cupon)
                                .addGap(18, 18, 18)
                                .addComponent(txtCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_validar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(rb_observacion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_subtotal)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                    .addComponent(lbl_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)))))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_subtotal)
                .addGap(11, 11, 11)
                .addComponent(lbl_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(rb_observacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_validar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb_cupon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCTO:");

        txtBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCodigoActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(110, 149, 106));
        jButton12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("FRECUENTES");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(110, 149, 106));
        btn_buscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtBuscarCodigo)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Producto buscarProductoPorNombre(String nombre) {
        ProductoController pc = new ProductoController();
        List<Producto> productos = pc.cargarProductos();

        for (Producto p : productos) {
            if (p.getNombre() != null && p.getNombre().equalsIgnoreCase(nombre.trim())) {
                return p;
            }
        }
        return null;
    }

    private void agregarAlCarrito(Producto p, int cantidad) {
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();

        double subtotal = p.getPrecioVenta()* cantidad;

        Object[] fila = {
            p.getNombre(),
            cantidad,
            subtotal
        };

        modeloCarrito.addRow(fila);

        calcularTotalVenta(); // recalcular el total
    }



    // Limpia el carrito — llamado desde la boleta después de confirmar venta
    public void vaciarCarrito() {
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
        modeloCarrito.setRowCount(0);
        spCantidad.setValue(1);
        lblTotal.setText("Total: S/ 0.00");
        txtObservaciones.setText("");
        txtCupon.setText("");
    }

// Recalcula y actualiza el label total — llamado desde la boleta después de actualizar inventario

    private void tb_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_reportesActionPerformed

    private void tb_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_entradaActionPerformed
        jFrame_Asistncias jFrame_Asistncias1;
        jFrame_Asistncias1 = new jFrame_Asistncias();
        jFrame_Asistncias1.setVisible(true);
    }//GEN-LAST:event_tb_entradaActionPerformed

    private void tb_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_ventasActionPerformed

    private void tb_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_cuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFrame_añadirProducto jFrame_añadirProducto1 = new jFrame_añadirProducto();
        jFrame_añadirProducto1.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        int filaSeleccionada = tablaProductos.getSelectedRow();
        if (filaSeleccionada != -1) {

            String nombre = tablaProductos.getValueAt(filaSeleccionada, 0).toString();
            double precio = Double.parseDouble(tablaProductos.getValueAt(filaSeleccionada, 1).toString());
            int stock = Integer.parseInt(tablaProductos.getValueAt(filaSeleccionada, 2).toString());
            String codigo = tablaProductos.getValueAt(filaSeleccionada, 3).toString();

            int cantidad = (Integer) spCantidad.getValue();

            if (cantidad > stock) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay suficiente stock.");
                return;
            }

            double subtotal = precio * cantidad;

            DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
            Object[] fila = {nombre, cantidad, subtotal};
            modeloCarrito.addRow(fila);

            actualizarTotal();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto primero.");
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int fila = tablaProductos.getSelectedRow();
        if (fila != -1) {
            String nombre = tablaProductos.getValueAt(fila, 0).toString();
            String codigo = tablaProductos.getValueAt(fila, 3).toString();

            String reporte = JOptionPane.showInputDialog(this, "Ingrese el reporte del producto " + nombre + ":");

            if (reporte != null && !reporte.trim().isEmpty()) {
                try (BufferedWriter bw = new BufferedWriter(new FileWriter("reportes.txt", true))) {
                    bw.write("Producto: " + nombre + " (" + codigo + ") - Reporte: " + reporte);
                    bw.newLine();
                    JOptionPane.showMessageDialog(this, "Reporte guardado correctamente.");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el reporte.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para reportar.");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Cambiar texto y bloquear botón mientras simula escaneo
        jButton6.setText("Escaneando...");
        jButton6.setEnabled(false);

        // Crear Timer (no repetir) que ejecuta la acción tras 2000 ms
        Timer t = new Timer(2000, e -> {
            ProductoController pc = new ProductoController();
            List<Producto> productos = pc.cargarProductos();

            if (productos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay productos cargados.");
            } else {
                Random rand = new Random();
                Producto p = productos.get(rand.nextInt(productos.size()));

                int cantidad = 1; // cantidad por defecto al escanear
                if (p.getStock() > 0) {
                    double subtotal = p.getPrecioVenta()* cantidad;

                    DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
                    modeloCarrito.addRow(new Object[]{p.getNombre(), cantidad, subtotal});

                    // recalcula total con tu método existente
                    actualizarTotal();

                    JOptionPane.showMessageDialog(this, "Producto escaneado: " + p.getNombre());
                } else {
                    JOptionPane.showMessageDialog(this, "El producto " + p.getNombre() + " no tiene stock.");
                }
            }

            // Restaurar el botón
            jButton6.setText("ESCANEAR SKU");
            jButton6.setEnabled(true);
        });

        t.setRepeats(false); // IMPORTANT: setRepeats devuelve void, no se puede encadenar
        t.start();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        javax.swing.table.DefaultTableModel modeloCarrito = (javax.swing.table.DefaultTableModel) miniTabla.getModel();
        modeloCarrito.setRowCount(0);      // vacía el carrito
        spCantidad.setValue(1);       // reiniciar spinner (ajusta el nombre a tu spinner)
        lblTotal.setText("Total: S/ 0.00"); // reset total (ajusta el formato si quieres)
        // Opcional: limpiar observaciones, cupones, etc.
        txtObservaciones.setText("");
        txtCupon.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        DefaultTableModel carrito = (DefaultTableModel) miniTabla.getModel();
        DefaultTableModel carritoClonado = new DefaultTableModel(new Object[]{"Producto", "Cantidad", "Subtotal"}, 0);

        for (int i = 0; i < carrito.getRowCount(); i++) {
            Object[] fila = {
                carrito.getValueAt(i, 0),
                carrito.getValueAt(i, 1),
                carrito.getValueAt(i, 2)
            };
            carritoClonado.addRow(fila);
        }

        // 👇 Aquí recogemos lo que ya tienes en tus labels del MenuPrincipal
        String subtotal = lbl_subtotal.getText().replace("Subtotal: ", "");
        String descuento = lbl_descuento.getText().replace("Descuento: ", "");
        String total = lblTotal.getText().replace("Total: ", "");

        // 👇 Usamos el nuevo constructor de la boleta
        jFrame_GenerarBoleta ventanaBoleta = new jFrame_GenerarBoleta(
                this,
                carritoClonado,
                subtotal,
                descuento,
                total
        );

        ventanaBoleta.setLocationRelativeTo(this);
        ventanaBoleta.setAlwaysOnTop(true);
        ventanaBoleta.setVisible(true);
        ventanaBoleta.toFront();
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void rb_observacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_observacionActionPerformed
        txtObservaciones.setEnabled(rb_observacion.isSelected());
    }//GEN-LAST:event_rb_observacionActionPerformed

// Recalcula y actualiza el label total — llamado desde la boleta después de actualizar inventario
    public void actualizarTotal() {
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
        double subtotal = 0;

        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            Object v = modeloCarrito.getValueAt(i, 2);
            try {
                subtotal += Double.parseDouble(String.valueOf(v));
            } catch (Exception ex) {
                // ignorar fila inválida
            }
        }

        // Mostrar subtotal real del carrito
        lbl_subtotal.setText(String.format("Subtotal: "+"S/ %.2f", subtotal));

        // Por defecto el total = subtotal (sin cupón aplicado aún)
        lblTotal.setText(String.format("TOTAL: "+"S/ %.2f", subtotal));

        // Resetear el label de descuento
        lbl_descuento.setText("Sin descuento");
    }
    private void calcularTotalVenta() {
        DefaultTableModel modeloCarrito = (DefaultTableModel) miniTabla.getModel();
        double total = 0;

        for (int i = 0; i < modeloCarrito.getRowCount(); i++) {
            total += (double) modeloCarrito.getValueAt(i, 2); // columna Precio (subtotal)
        }

        lblTotal.setText("Total: S/ " + total);
    }

    private void rb_cuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cuponActionPerformed
        txtCupon.setEnabled(rb_cupon.isSelected());
    }//GEN-LAST:event_rb_cuponActionPerformed

    private void txtBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCodigoActionPerformed

    }//GEN-LAST:event_txtBuscarCodigoActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        ProductoController pc = new ProductoController();
        List<Producto> productos = pc.cargarProductos();

        // Ordenar por vendidos (descendente)
        productos.sort((p1, p2) -> Integer.compare(p2.getVendidos(), p1.getVendidos()));

        // Mostrar en tablaProductos
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);

        for (Producto p : productos) {
            modelo.addRow(new Object[]{p.getNombre(), p.getPrecioVenta(), p.getStock(), p.getVendidos()});
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String textoBusqueda = txtBuscarCodigo.getText().trim();
        if (textoBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un código o nombre para buscar.");
            return;
        }

        ProductoController pc = new ProductoController();
        List<Producto> productos = pc.cargarProductos();

        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        boolean encontrado = false;
        for (Producto p : productos) {
            if (p.getCodigo().equalsIgnoreCase(textoBusqueda)
                    || p.getNombre().equalsIgnoreCase(textoBusqueda)) {
                modelo.addRow(new Object[]{p.getNombre(), p.getPrecioVenta(), p.getStock(), p.getCodigo(), p.getVendidos()});
                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_actualizarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarItemActionPerformed
        int fila = miniTabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para actualizar.");
            return;
        }

        int nuevaCantidad = (int) sp_item.getValue();
        if (nuevaCantidad <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) miniTabla.getModel();
        double precioUnitario = Double.parseDouble(modelo.getValueAt(fila, 2).toString());

        // actualizar cantidad y subtotal
        modelo.setValueAt(nuevaCantidad, fila, 1);
        modelo.setValueAt(precioUnitario * nuevaCantidad, fila, 2);

        actualizarTotal(); // recalcula el total después de actualizar
    }//GEN-LAST:event_btn_actualizarItemActionPerformed

    private void btn_eliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarItemActionPerformed
        int fila = miniTabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para eliminar.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este producto?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel modelo = (DefaultTableModel) miniTabla.getModel();
            modelo.removeRow(fila);
            actualizarTotal(); // recalcula el total después de eliminar
        }
    }//GEN-LAST:event_btn_eliminarItemActionPerformed

    private void btn_validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validarActionPerformed
        String cupon = txtCupon.getText().trim();

        if (cupon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un cupón primero.");
            return;
        }

        PromocionController promoCtrl = new PromocionController();
        double subtotal = calcularSubtotalCarrito();

        double totalConCupon = promoCtrl.aplicarCupon(cupon, subtotal);

        if (totalConCupon < subtotal) {
            JOptionPane.showMessageDialog(this, "Cupón válido: 10% de descuento aplicado.");
            lbl_descuento.setText("Cupón aplicado: 10%");
            lblTotal.setText(String.format("S/ %.2f", totalConCupon));
        } else {
            JOptionPane.showMessageDialog(this, "Cupón inválido o caducado.");
            lbl_descuento.setText("Sin descuento");
            lblTotal.setText(String.format("S/ %.2f", subtotal));
        }
    }//GEN-LAST:event_btn_validarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuPrincipal().setVisible(true);

            }
        });

    }

    private double calcularSubtotalCarrito() {
        double total = 0.0;
        DefaultTableModel carrito = (DefaultTableModel) miniTabla.getModel();

        for (int i = 0; i < carrito.getRowCount(); i++) {
            double subtotal = Double.parseDouble(carrito.getValueAt(i, 2).toString());
            total += subtotal;
        }
        return total;
    }

    private void actualizarTotales() {
        double subtotal = calcularSubtotalCarrito();
        lbl_subtotal.setText(String.format("S/ %.2f", subtotal));

        // Por defecto, total = subtotal si no hay descuentos
        lblTotal.setText(String.format("S/ %.2f", subtotal));
        lbl_descuento.setText("Sin descuento");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarItem;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminarItem;
    private javax.swing.JButton btn_validar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lbl_descuento;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JRadioButton rb_cupon;
    private javax.swing.JRadioButton rb_observacion;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JSpinner sp_item;
    private javax.swing.JToggleButton tb_cuenta;
    private javax.swing.JToggleButton tb_entrada;
    private javax.swing.JToggleButton tb_reportes;
    private javax.swing.JToggleButton tb_ventas;
    private javax.swing.JTextField txtBuscarCodigo;
    private javax.swing.JTextField txtCupon;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
