/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.UPAO.proyecto.app;

/**
 *
 * @author WIN-10
 */
public class PROMOCIONES extends javax.swing.JFrame {

    /**
     * Creates new form PROMOCIONES
     */
    public PROMOCIONES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTop = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblFrase = new javax.swing.JLabel();
        panelTitle = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelKPIs = new javax.swing.JPanel();
        kpiVentasIncrementales = new javax.swing.JPanel();
        lblKpi1Titulo = new javax.swing.JLabel();
        lblKpi1Valor = new javax.swing.JLabel();
        kpiUplift = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kpiTickets = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kpiMargen = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        panelFiltros = new javax.swing.JPanel();
        lblFiltrarPor = new javax.swing.JLabel();
        cmbTienda = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        btnFecha = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnExportar = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelListado = new javax.swing.JPanel();
        lblListado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPromos = new javax.swing.JTable();
        panelBotonesListado = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnDuplicar = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEvaluarImpacto = new javax.swing.JButton();
        panelDetalle = new javax.swing.JPanel();
        lblDetalle = new javax.swing.JLabel();
        panelTabs = new javax.swing.JTabbedPane();
        panelForm = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        cmbTipoPromo = new javax.swing.JComboBox<>();
        txtProductos = new javax.swing.JTextField();
        cmbTiendaForm = new javax.swing.JComboBox<>();
        dateInicio = new javax.swing.JButton();
        dateFin = new javax.swing.JButton();
        spnDescuento = new javax.swing.JSpinner();
        txtPrecioPromo = new javax.swing.JTextField();
        txtObjetivo = new javax.swing.JTextField();
        txtPresupuesto = new javax.swing.JTextField();
        cmbEstadoForm = new javax.swing.JComboBox<>();
        cmbCanal = new javax.swing.JComboBox<>();
        panelFormButtons = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPrevisualizar = new javax.swing.JButton();
        panelImpacto = new javax.swing.JPanel();
        panelSubFiltros = new javax.swing.JPanel();
        cmbBaseline = new javax.swing.JComboBox<>();
        cmbPeriodoImpacto = new javax.swing.JComboBox<>();
        btnRefrescarImpacto = new javax.swing.JButton();
        panelCharts = new javax.swing.JPanel();
        panelChartVentas = new javax.swing.JPanel();
        lblVentasTitulo = new javax.swing.JLabel();
        panelChartTickets = new javax.swing.JPanel();
        lblMargenTitulo = new javax.swing.JLabel();
        panelChartMargen = new javax.swing.JPanel();
        lblTicketsTitulo = new javax.swing.JLabel();
        panelMediosPago = new javax.swing.JPanel();
        lblMediosPagoTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTop.setLayout(new java.awt.BorderLayout());

        panelHeader.setBackground(new java.awt.Color(255, 153, 0));
        panelHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 16, 0, 16));
        panelHeader.setPreferredSize(new java.awt.Dimension(780, 70));
        panelHeader.setLayout(new java.awt.BorderLayout());

        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\WIN-10\\OneDrive\\Imágenes\\Logo_kuyay-convertido-a-pequeño-removebg-preview.png")); // NOI18N
        panelHeader.add(logoLabel, java.awt.BorderLayout.WEST);

        btnSalir.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelHeader.add(btnSalir, java.awt.BorderLayout.EAST);

        lblFrase.setFont(new java.awt.Font("Harlow Solid Italic", 0, 12)); // NOI18N
        lblFrase.setForeground(new java.awt.Color(193, 28, 28));
        lblFrase.setText("Todo lo que necesitas al alcance");
        panelHeader.add(lblFrase, java.awt.BorderLayout.CENTER);

        panelTop.add(panelHeader, java.awt.BorderLayout.NORTH);

        panelTitle.setBackground(new java.awt.Color(153, 0, 0));
        panelTitle.setPreferredSize(new java.awt.Dimension(780, 40));
        panelTitle.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PROMOCIONES");
        panelTitle.add(lblTitulo, java.awt.BorderLayout.CENTER);

        panelTop.add(panelTitle, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelTop, java.awt.BorderLayout.NORTH);

        panelKPIs.setLayout(new java.awt.GridLayout(4, 1));

        kpiVentasIncrementales.setBackground(new java.awt.Color(102, 102, 255));
        kpiVentasIncrementales.setForeground(new java.awt.Color(255, 255, 255));
        kpiVentasIncrementales.setLayout(new java.awt.BorderLayout());

        lblKpi1Titulo.setForeground(new java.awt.Color(255, 255, 255));
        lblKpi1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKpi1Titulo.setText("VENTAS INCREMENTALES (S/)");
        kpiVentasIncrementales.add(lblKpi1Titulo, java.awt.BorderLayout.PAGE_START);

        lblKpi1Valor.setForeground(new java.awt.Color(255, 255, 255));
        lblKpi1Valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKpi1Valor.setText("jLabel2");
        kpiVentasIncrementales.add(lblKpi1Valor, java.awt.BorderLayout.CENTER);

        panelKPIs.add(kpiVentasIncrementales);

        kpiUplift.setBackground(new java.awt.Color(0, 153, 0));
        kpiUplift.setLayout(new java.awt.BorderLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("UPLIFT (%)");
        kpiUplift.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");
        kpiUplift.add(jLabel4, java.awt.BorderLayout.CENTER);

        panelKPIs.add(kpiUplift);

        kpiTickets.setBackground(new java.awt.Color(255, 102, 0));
        kpiTickets.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TICKETS EXTRAS");
        kpiTickets.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");
        kpiTickets.add(jLabel6, java.awt.BorderLayout.CENTER);

        panelKPIs.add(kpiTickets);

        kpiMargen.setBackground(new java.awt.Color(255, 0, 51));
        kpiMargen.setLayout(new java.awt.BorderLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MARGEN ADICIONAL (S/)");
        kpiMargen.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");
        kpiMargen.add(jLabel8, java.awt.BorderLayout.CENTER);

        panelKPIs.add(kpiMargen);

        getContentPane().add(panelKPIs, java.awt.BorderLayout.LINE_START);

        panelBody.setBackground(new java.awt.Color(219, 236, 232));
        panelBody.setLayout(new java.awt.BorderLayout());

        panelFiltros.setBackground(new java.awt.Color(219, 236, 232));
        panelFiltros.setLayout(new java.awt.GridBagLayout());

        lblFiltrarPor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFiltrarPor.setForeground(new java.awt.Color(0, 0, 0));
        lblFiltrarPor.setText("FILTRAR POR:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFiltros.add(lblFiltrarPor, gridBagConstraints);

        cmbTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ventas (S/), ", "Transacciones ", "Margen %", "Ticket Promedio" }));
        cmbTienda.setPreferredSize(new java.awt.Dimension(160, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFiltros.add(cmbTienda, gridBagConstraints);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ranking", "vs periodo anterior ", "A vs B" }));
        cmbEstado.setPreferredSize(new java.awt.Dimension(160, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFiltros.add(cmbEstado, gridBagConstraints);

        btnFecha.setText("FECHA");
        btnFecha.setPreferredSize(new java.awt.Dimension(120, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFiltros.add(btnFecha, gridBagConstraints);

        txtBuscar.setText("Buscar promo / producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFiltros.add(txtBuscar, gridBagConstraints);

        btnExportar.setText("EXPORTAR");
        btnExportar.setPreferredSize(new java.awt.Dimension(120, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFiltros.add(btnExportar, gridBagConstraints);

        panelBody.add(panelFiltros, java.awt.BorderLayout.PAGE_START);

        panelListado.setLayout(new java.awt.BorderLayout());

        lblListado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListado.setText("PROMOCIONES");
        panelListado.add(lblListado, java.awt.BorderLayout.PAGE_START);

        tblPromos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Producto(s)", "Tienda", "Inicio", "Fin", "Descuento", "Objetivo", "Estado"
            }
        ));
        tblPromos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblPromos);

        panelListado.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelBotonesListado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnCrear.setText("CREAR");
        panelBotonesListado.add(btnCrear);

        btnDuplicar.setText("DUPLICAR");
        panelBotonesListado.add(btnDuplicar);

        btnActivar.setText("ACTIVAR");
        panelBotonesListado.add(btnActivar);

        btnDesactivar.setText("DESACTIVAR");
        panelBotonesListado.add(btnDesactivar);

        btnEditar.setText("EDITAR");
        panelBotonesListado.add(btnEditar);

        btnEvaluarImpacto.setText("EVALUAR IMPACTO");
        panelBotonesListado.add(btnEvaluarImpacto);

        panelListado.add(panelBotonesListado, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setLeftComponent(panelListado);

        panelDetalle.setLayout(new java.awt.BorderLayout());

        lblDetalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDetalle.setText("DETALLE/EDICION");
        panelDetalle.add(lblDetalle, java.awt.BorderLayout.PAGE_START);

        panelForm.setLayout(new java.awt.GridBagLayout());

        txtNombre.setText("Nombre...");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(txtNombre, gridBagConstraints);

        cmbTipoPromo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(cmbTipoPromo, gridBagConstraints);

        txtProductos.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(txtProductos, gridBagConstraints);

        cmbTiendaForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(cmbTiendaForm, gridBagConstraints);

        dateInicio.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(dateInicio, gridBagConstraints);

        dateFin.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(dateFin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(spnDescuento, gridBagConstraints);

        txtPrecioPromo.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(txtPrecioPromo, gridBagConstraints);

        txtObjetivo.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(txtObjetivo, gridBagConstraints);

        txtPresupuesto.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(txtPresupuesto, gridBagConstraints);

        cmbEstadoForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(cmbEstadoForm, gridBagConstraints);

        cmbCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        panelForm.add(cmbCanal, gridBagConstraints);

        panelFormButtons.setLayout(new java.awt.GridBagLayout());

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelFormButtons.add(btnGuardar, gridBagConstraints);

        btnCancelar.setText("CANCELAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelFormButtons.add(btnCancelar, gridBagConstraints);

        btnPrevisualizar.setText("PREVISUALIZAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelFormButtons.add(btnPrevisualizar, gridBagConstraints);

        panelForm.add(panelFormButtons, new java.awt.GridBagConstraints());

        panelTabs.addTab("FORMULARIO", panelForm);

        panelImpacto.setLayout(new java.awt.BorderLayout());

        panelSubFiltros.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        cmbBaseline.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelSubFiltros.add(cmbBaseline);

        cmbPeriodoImpacto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Durante", "Despues", " " }));
        panelSubFiltros.add(cmbPeriodoImpacto);

        btnRefrescarImpacto.setText("jButton1");
        panelSubFiltros.add(btnRefrescarImpacto);

        panelImpacto.add(panelSubFiltros, java.awt.BorderLayout.PAGE_START);

        panelCharts.setLayout(new java.awt.GridLayout(2, 2, 16, 16));

        panelChartVentas.setLayout(new java.awt.BorderLayout());

        lblVentasTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasTitulo.setText("VENTAS ANTES vs DURANTE");
        panelChartVentas.add(lblVentasTitulo, java.awt.BorderLayout.PAGE_START);

        panelCharts.add(panelChartVentas);

        panelChartTickets.setLayout(new java.awt.BorderLayout());

        lblMargenTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMargenTitulo.setText("MARGEN");
        panelChartTickets.add(lblMargenTitulo, java.awt.BorderLayout.PAGE_START);

        panelCharts.add(panelChartTickets);

        panelChartMargen.setLayout(new java.awt.BorderLayout());

        lblTicketsTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTicketsTitulo.setText("TICKET PROMEDIO");
        panelChartMargen.add(lblTicketsTitulo, java.awt.BorderLayout.PAGE_START);

        panelCharts.add(panelChartMargen);

        panelMediosPago.setLayout(new java.awt.BorderLayout());

        lblMediosPagoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMediosPagoTitulo.setText("MEDIOS DE PAGO");
        panelMediosPago.add(lblMediosPagoTitulo, java.awt.BorderLayout.PAGE_START);

        panelCharts.add(panelMediosPago);

        panelImpacto.add(panelCharts, java.awt.BorderLayout.CENTER);

        panelTabs.addTab("IMPACTO", panelImpacto);

        panelDetalle.add(panelTabs, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(panelDetalle);

        panelBody.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBody, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Panel_Gerente g = new Panel_Gerente(); // cambia por el nombre de tu JFrame de Gerente
        g.setVisible(true);
        g.setLocationRelativeTo(null); // centrar la ventana en la pantalla

        // Cerrar esta ventana (PERSONAL)
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROMOCIONES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROMOCIONES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROMOCIONES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROMOCIONES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROMOCIONES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnDuplicar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEvaluarImpacto;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPrevisualizar;
    private javax.swing.JButton btnRefrescarImpacto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbBaseline;
    private javax.swing.JComboBox<String> cmbCanal;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbEstadoForm;
    private javax.swing.JComboBox<String> cmbPeriodoImpacto;
    private javax.swing.JComboBox<String> cmbTienda;
    private javax.swing.JComboBox<String> cmbTiendaForm;
    private javax.swing.JComboBox<String> cmbTipoPromo;
    private javax.swing.JButton dateFin;
    private javax.swing.JButton dateInicio;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel kpiMargen;
    private javax.swing.JPanel kpiTickets;
    private javax.swing.JPanel kpiUplift;
    private javax.swing.JPanel kpiVentasIncrementales;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblFiltrarPor;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblKpi1Titulo;
    private javax.swing.JLabel lblKpi1Valor;
    private javax.swing.JLabel lblListado;
    private javax.swing.JLabel lblMargenTitulo;
    private javax.swing.JLabel lblMediosPagoTitulo;
    private javax.swing.JLabel lblTicketsTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVentasTitulo;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelBotonesListado;
    private javax.swing.JPanel panelChartMargen;
    private javax.swing.JPanel panelChartTickets;
    private javax.swing.JPanel panelChartVentas;
    private javax.swing.JPanel panelCharts;
    private javax.swing.JPanel panelDetalle;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelFormButtons;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelImpacto;
    private javax.swing.JPanel panelKPIs;
    private javax.swing.JPanel panelListado;
    private javax.swing.JPanel panelMediosPago;
    private javax.swing.JPanel panelSubFiltros;
    private javax.swing.JTabbedPane panelTabs;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel panelTop;
    private javax.swing.JSpinner spnDescuento;
    private javax.swing.JTable tblPromos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObjetivo;
    private javax.swing.JTextField txtPrecioPromo;
    private javax.swing.JTextField txtPresupuesto;
    private javax.swing.JTextField txtProductos;
    // End of variables declaration//GEN-END:variables
}
